### ISSUE TITLE
practica 1 unidad 4 conexion de base de datos

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/conexion-bases-de-datos-topicos4semestre2022#1]
[topicos unidad 4  actividad 1practica acceso de datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-topicos4semestre2022/files/8893297/topicos.unidad.4.actividad.1practica.acceso.de.datos.pdf)

**Comment by RaelRGB** [comment]
18.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
